version: '3.3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: license-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8090:8080' #Port außerhalb:Port innerhalb